name: Secrets & variables sync action
author: Jacob Hummer <jcbhmr@outlook.com> (https://jcbhmr.me/)
description: ⚙️ Set & delete secrets or variables on multiple repos at once!
branding:
  icon: lock
  color: yellow
inputs:
  token:
    required: true
  github-server-url:
    required: true
    default: ${{ github.server_url }}
  dry-run:
    required: true
    default: false
  mode: {}
  repository: {}
  repositories: {}
  query: {}
  secret: {}
  secrets: {}
  variable: {}
  variables: {}
  organization: {}
  user: {}
  app:
    required: true
    default: actions
  environment: {}
  visibility:
    required: true
    default: all
runs:
  using: composite
  steps:
    - if: inputs.mode == 'set-secrets' || inputs.mode == 'set-secret'
      uses: jcbhmr/set-secrets@main
      with:
        token: ${{ inputs.token }}
        github-server-url: ${{ inputs.github-server-url }}
        dry-run: ${{ inputs.dry-run }}
        repository: ${{ inputs.repository }}
        repositories: ${{ inputs.repositories }}
        query: ${{ inputs.query }}
        secret: ${{ inputs.secret }}
        secrets: ${{ inputs.secrets }}
        organization: ${{ inputs.organization }}
        user: ${{ inputs.user }}
        app: ${{ inputs.app }}
        environment: ${{ inputs.environment }}
        visibility: ${{ inputs.visibility }}
    - if: inputs.mode == 'delete-secrets' || inputs.mode == 'delete-secret'
      uses: jcbhmr/delete-secrets@main
      with:
        token: ${{ inputs.token }}
        github-server-url: ${{ inputs.github-server-url }}
        dry-run: ${{ inputs.dry-run }}
        repository: ${{ inputs.repository }}
        repositories: ${{ inputs.repositories }}
        query: ${{ inputs.query }}
        secret: ${{ inputs.secret }}
        secrets: ${{ inputs.secrets }}
        organization: ${{ inputs.organization }}
        user: ${{ inputs.user }}
        app: ${{ inputs.app }}
        environment: ${{ inputs.environment }}
    # TODO: variables!
