name: Set secrets action
author: Jacob Hummer <jcbhmr@outlook.com> (https://jcbhmr.me/)
description: ⚙️ Set secrets or variables on multiple repos at once!
branding:
  icon: lock
  color: yellow
inputs:
  token:
    description: >
      The GitHub PAT to use when setting secrets on other repos. You can't use
      the default secrets.GITHUB_TOKEN for this since it only covers the current
      repository. You'll need to create a PAT with access to the "secrets"
      permission either for a single repo, multiple repos, or all repos. This
      is required.
    required: true
  github-server-url:
    description: >
      The GitHub server URL to use when setting secrets on other repos. This
      defaults to the GitHub server URL that the action is running on. Defaults
      to the github.server_url context variable.
    required: true
    default: ${{ github.server_url }}
  dry-run:
    description: >
      Whether or not to actually set the secrets. Set this to true when testing
      this action. Defaults to false.
    required: true
    default: false
runs:
  using: composite
  steps:
    - run: '"${GITHUB_ACTION_PATH%/}/cliw"'
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_GITHUB_SERVER_URL: ${{ inputs.github-server-url }}
        INPUT_DRY_RUN: ${{ inputs.dry-run }}
